name: annot_transformer
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - seaborn
  - numpy 
  - matplotlib 
  - spacy 
  - torchvision
  - pytorch=0.3.0
  - cudatoolkit=8.0
  - pip:
    - torchtext
